test = {   'name': 'q_voting_change',
    'points': 8,
    'suites': [   {   'cases': [   {   'code': ">>> np.isclose(voting_change.where('state', 'COLORADO')['std_pct_citizen_voted_2016'][0], 69.30073997045474, atol=.001)\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> np.isclose(voting_change.where('state', 'COLORADO')['std_pct_citizen_voted_2012'][0], 70.58867729165458, atol=.001)\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> np.isclose(voting_change.where('state', 'FLORIDA')['std_pct_citizen_voted_2012'][0], 60.07007404167578, atol=.001)\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> np.isclose(voting_change.where('state', 'FLORIDA')['std_pct_citizen_voted_2016'][0], 58.321906338842204, atol=.001)\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
